name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  lottie: ^2.6.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3
  flutter_mobx: ^2.0.6+5
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.2.1
  mobx: ^2.2.0
  animated_theme_switcher: ^2.0.8
  dio: ^5.3.2
  infinite_scroll_pagination: ^4.0.0
  audioplayers: ^5.1.0
  font_awesome_flutter: ^10.5.0
  audio_video_progress_bar: ^2.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  pinput: ^3.0.1

  intl: ^0.17.0

  mailer: ^6.0.1
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  glass_kit: ^3.0.0
  glass: ^1.0.2+1
  fluttertoast: ^8.2.4
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2
  flutter_advanced_drawer: ^1.3.5
  image_picker: ^1.0.4
  intl_phone_field: ^3.2.0
  animated_search_bar: ^2.7.1
  anim_search_bar: ^2.0.3
  rive: ^0.12.3
  equatable: ^2.0.5
  bloc:
   
 


dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter  
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app_icon-removebg-preview.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/pokemons_types/
    - assets/images/technical_records_types/
    - assets/images/technical_machines_types/
    - assets/images/pokemons_generations/generation_1/
    - assets/images/pokemons_generations/generation_2/
    - assets/images/pokemons_generations/generation_3/
    - assets/images/pokemons_generations/generation_4/
    - assets/images/pokemons_generations/generation_5/
    - assets/images/pokemons_generations/generation_6/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_8/
    - assets/lotties/
    - assets/images/pokemons_types/20/water.png
    - assets/images/R.jpg
    - assets/images/poke.jpg
    - assets/images/sliver.jpg
    - assets/images/poke.png 
    - assets/images/pokebg.png  
    - assets/images/pokedexbg05.png 
    - assets/images/pokedexbg06.png 
    - assets/images/bgblue0.png         
    - assets/images/pokeforest02.png
    - assets/images/bgblue01.png   
    - assets/images/pokeavatar.png 
    - assets/images/pokesignbg.png
    - assets/images/pikachufemale.png
    - assets/images/pokegradient.png
    - assets/images/BgPoke1.png
    - assets/news.json
    - assets/Rive/icons.riv


